title: Cynthia Hall
author: Cynthia Hall
email: cynthia.r.hall@nasa.gov
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my description

# social links
twitter_username: cyndibughall # DO NOT include the @ character, or else the build will fail!
github_username:  chall-nasa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
